name: 08 - Using Variables

on:
    push:
    workflow_dispatch:
Env:
    WORKFLOW_VAR: 'I am a workflow env var'
jobs:
    echo:
        runs-on: ubuntu-latest
        env:
            JOB_VAR:  'I am a job env var'
        steps:
            - name: Print Env Variables
              env:
                STEP_VAR: "I am a step env var"
                step_var2: 'I am another step env var'
              run: |
               echo "Step env var: ${{  env.STEP_VAR }}"
               echo "Step env var2: $step_Var2"
               echo "Job env var: ${{ env.JOB_VAR }}"
               echo "Job env var: ${{ env.WORKFLOW_VAR }}"